nlprun -m jagupard24 -g 0 -r 40G -o logs/chomsky_f1.log "bash run_chomsky.sh 1"
nlprun -m jagupard27 -g 0 -r 40G -o logs/chomsky_f2.log "bash run_chomsky.sh 2"
nlprun -m jagupard28 -g 0 -r 40G -o logs/chomsky_f4.log "bash run_chomsky.sh 4"
# nlprun -m jagupard26 -g 0 -r 40G -o logs/chomsky_f8.log "bash run_chomsky.sh 8"
# nlprun -m jagupard26 -g 0 -r 40G -o logs/chomsky_f16.log "bash run_chomsky.sh 16"
# nlprun -m jagupard26 -g 0 -r 40G -o logs/chomsky_f32.log "bash run_chomsky.sh 32"